### ISSUE TITLE
Add Mysqlproxy by default

### ISSUE THREAD

**Issue by Plopix** [ezsystems/launchpad#42]
```
    profiledb:
        image: plopix/docker-mysqlproxyprofiler
        environment:
            - 'BACKEND=db:3306'
```
